###

GET http://localhost:3003/acounts


###
GET http://localhost:3003/acount/balance?cpf=777.888.999-00

###
POST http://localhost:3003/acount/createAcount
Content-Type: application/json

{
    "name": "Alberto Roberto",
    "cpf": "777.888.999-00",
    "birthDate": "03/03/2003",
    "balance": 50
}

//###
//PUT http://localhost:3003/users
//Content-Type: application/json

//{
//    "id": 7,
//    "name": "Ricardo Ribeiro",
//    "email": "rickhard@bol.com.br",
//    "type": "ADMIN",
//    "age": 50
//}